### ISSUE TITLE
Fix twitter for the greater good

### ISSUE THREAD

**Issue by d-hain** [ThePrimeagen/i-fixed#2]
I would do it myself but I don't really have time tonight. I’m meeting a girl (a real one) in half an hour (wouldn’t expect a lot of you to understand anyway) so please don’t DM me asking me where I am (I'm with the girl, ok) you’ll most likely get aired because ill be with the girl (again I don’t expect you to understand) shes actually really interested in me and its not a situation I can pass up for just fixing Twitter (because i'll be meeting a girl, not that you really are going to understand) this is my life now. Meeting women and not wasting my precious time coding, I have to move on from such simple things and branch out (you wouldn't understand).

**Comment by ThePrimeagen** [comment]
pretty sure you mean arch
